language: java

notifications:
  email: false

services:
  - postgresql

before_script:
  - psql -c "create database games_db" -U postgres
  - psql -c "create database users_db" -U postgres
  - psql -c "create database reviews_db" -U postgres
  - psql -c "create role program WITH password 'test'" -U postgres
  - psql -c "grant all privileges ON database games_db TO program" -U postgres
  - psql -c "grant all privileges ON database users_db TO program" -U postgres
  - psql -c "grant all privileges ON database reviews_db TO program" -U postgres
  - psql -c "alter role program WITH login" -U postgres

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

